/**
 * Utility class for lists of topics
 */

export const AVAILABLE_TOPICS = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Statistics",
  "Economics",
  "Business Studies",
  "Accounting",
  "Finance",
  "Marketing",
  "Law",
  "Political Science",
  "History",
  "Art History",
  "Geography",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Environmental Science",
  // Languages
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Chinese",
  "Japanese",
  "Korean",
  "Russian",
  "Arabic",
  "Hindi",
  // Music
  "Piano",
  "Guitar",
  "Violin",
  "Flute",
  "Saxophone",
  "Drums",
  "Trumpet",
  "Singing",
  "Music Theory",
  "Music Production",
  // Arts
  "Drawing",
  "Painting",
  "Photography",
  "Graphic Design",
  "Creative Writing",
  "Film Studies",
  // Professional Skills
  "Public Speaking",
  "Interview Preparation",
  "Resume Writing",
  "Project Management",
  "Data Analysis",
  "Digital Marketing",
];

export const POPULAR_TOPICS = [
  "Mathematics",
  "Spanish",
  "German",
  "English",
  "Piano",
  "Guitar",
  "Biology",
  "History",
  "Chemistry",
];
