# Generated by Django 5.1.3 on 2025-04-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
    ]
